### ISSUE TITLE
Required for Chromium, Edge, & other derivatives?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardMV3#30]
I can't seem to find a straight answer to this:  How deep & far-reaching is the change mentioned on httpS://adguard.com/blog/adguard-mv3.html?  Will it affect Chromium, Edge, & other derivatives (so we need to use this version next year for them, also) or just Chrome (so the rest of us are fine)?  If the first, then it'd be amazing to publish this to, e.g., Edge Addons, so it can be tested in more locked-down environments.  Else, encourage folks to move away from Chrome.

N.B.: It'd be useful to mention this answer clearly in the official places (this repo's main ReadMe, that blog post, &c).

**Comment by 105th** [comment]
@TPS, as far as I know, [Edge](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3) and [Firefox](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/) have also supported Manifest V3. but Firefox will continue to support blocking WebRequests as well as DeclarativeNetRequest, because in their opinion - both technologies have their advantages and disadvantages.
As for Edge and Chrome - the move to Manifest V3 will really be a "game changer," and we're trying to test how that works for Chrome first ([here](https://github.com/AdguardTeam/tsurlfilter/tree/epic/tswebextension/packages/tsurlfilter/src/rules/declarative-converter#table-of-contents) you can find the whole list of our modifiers and their statuses about their work in MV3). And after that, we'll publish an MV3 version for Edge, I guess.

And, of course, our main system ad blocker is much more powerful than the browser extension.

**Comment by TPS** [comment]
Will these & related changes affect the main AdGuard desktop editions? E.g., I see experimental flags testing not allowing injected scripts, &, which make me think this won't be the only change made simultaneously to disable/cripple adblocking.

**Comment by Birbber** [comment]
Desktop applications can't affect browser settings. 
I'm closing this issue as completed. Please create a new one if you still have questions.
